language: scala

jdk:
  - oraclejdk8
scala:
   - 2.11.6
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test scalastyle

  # Trick to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  - sbt coveralls

notifications:
  email:
    recipients:
      - javier.rf91@gmail.com