language: scala

jdk:
  - oraclejdk8
scala:
   - 2.11.6
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

script:
  - sbt clean coverage test coverageReport

  # Trick to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 7f849894-b0e2-4032-8692-b07485b01896

notifications:
  email:
    recipients:
      - javier.rf91@gmail.com